swagger: "2.0"
info:
  description: "Simple Users REST API"
  version: "1.0.0"
  title: "NodeJS Exercise"
  contact:
    email: "manulei@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/"
tags:
- name: "users"
  description: "Operations on the user"
schemes:
- "http"
paths:
  /users:
    get:
      tags:
      - "users"
      summary: "Get users"
      description: "Get all users in the system"
      operationId: "getUsers"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                name:
                  type: string
                email:
                  type: string
    post:
      tags:
      - "users"
      summary: "Create user"
      description: "Create a new user"
      operationId: "createUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "user"
        description: "User to be created"
        required: true
        schema:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            password:
              type: string
          
      responses:
        "201":
          description: "successful operation - returnes the added user"
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              email:
                type: string
        "422":
          description: "invalid parameters supplied"
  /users/{userId}:
    delete:
      tags:
      - "users"
      summary: "Delete user"
      description: "Delete a user from the db by userId"
      operationId: "deleteUser"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "The id that needs to be deleted"
        required: true
        type: "integer"
      responses:
        "422":
          description: "Invalid user id supplied"
        "404":
          description: "User not found"
        "204":
          description: "Deleted successfully"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"