version: "3"

services:
    web:
        build: ./app
        container_name: lytx-rest-api
        ports:
            - "3000:3000"
        networks:
            lytx_net:
                ipv4_address: 172.28.1.1
        environment:
            - MYSQL_DB_USER=node
            - MYSQL_DB_PASS=12345678
            - MYSQL_DB_NAME=lytx
            - MYSQL_DB_HOST=172.28.1.2
            - MYSQL_DB_PORT=6603
    db:
        build: ./mysql
        container_name: lytx-mysql
        ports:
            - "6603:3306"
        networks:
            lytx_net:
                ipv4_address: 172.28.1.2
networks:
    lytx_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16